### ISSUE TITLE
Update keycloak Docker tag to v26

### ISSUE THREAD

**Issue by ManuelMoeri** [puzzle/okr#1079]
Beschrieb

### Anforderungen
- Anforderung

### Akzeptanzkriterien
- Akzeptanzkriterien

**Comment by clean-coder** [comment]
**Kurzanalyse**

Habe versucht das Problem etwas zu analysieren.

- der Import des realm-pitc.json schlägt fehl
- ich bin (neben SQL errors) auf folgende Error Message gestossen: KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists
- es scheint so zu sein, dass beim Import versucht wird ein User admin zu erstellen. Und dieser existiert bereits im json Dump. Man kann nun den Namen (im docker-compose.yml) von admin auf etwas andere anpassen, und Keycloak startet wieder und lokal kann ich sogar server und client starten und sich erfolgreich im OKR anmelden ... alles läuft wie gehabt. Intern wird in Keycloak dann einfach ein zusätzlicher User admin26 erstellt:

```
  keycloak-pitc:
    image: quay.io/keycloak/keycloak:26.0.1
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin26
      - KC_BOOTSTRAP_ADMIN_PASSWORD=keycloak26
```

- leider funktioniert aber cypress nicht mehr, weder lokal noch auf dem Build Server
