### ISSUE TITLE
Multitenancy E2E Tests automatisieren

### ISSUE THREAD

**Issue by janikEndtner** [puzzle/okr#923]

**Comment by MasterEvarior** [comment]
Eine Idee um die E2E-Tests (immerhin in der Pipeline) schneller zu machen, wäre es die Ausführung zu parallelisieren. 
Mithilfe der [Matrix-Strategie](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#using-a-matrix-strategy) könnte jedes ` .cy.ts`-File seperat, gleichzeitig ausgeführt werden. Ein Beispiel wie das aussehen könnte kann man [hier finden](https://www.lekoarts.de/garden/running-cypress-tests-with-github-actions-in-parallel/). 

Wichtig wäre auch noch, dass die Lösung automatisch alle verfügbaren `.cy.ts` Files  ausgewählt und diese nicht manuell nachgeführt werden müssen. Z.B. kann man die Files zu einem JSON-Array verarbeiten mit [jq](https://github.com/jqlang/jq) ` ls -1 "./cypress/e2e/" | jq -R . | jq -s .`  und dann [als Argument an den Matrix-Job weitergeben](https://stackoverflow.com/a/65434401).

**Comment by RandomTannenbaum** [comment]
**Stand 04.11.2024**
Heute habe ich zuerst mal bei allen inputs `delay: 0` hinzugefügt. Danach bin ich dem nachgegangen was @MasterEvarior in seinem Kommentar oben geschrieben hat. Das sollte eigentlich auch funktionieren, jedoch habe ich es noch nicht geschafft das richtige Format auszugeben damit die Matrix die Liste von files auch nimmt.

**Comment by MasterEvarior** [comment]
@RandomTannenbaum 
Hier ist Code den ich mal zum Laufen gebracht hatte, vielleicht hilft er dir weiter:
```
  gather-e2e-specs:
    runs-on: ubuntu-24.04
    outputs:
      specs: ${{ steps.gather.outputs.specs }}
    defaults:
      run:
        working-directory: frontend/cypress/e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt install jq

      - name: Gather specs
        id: gather
        run: |
          echo "Searching for specs at $(pwd)"
          specs=$(find * -maxdepth 1 -type f | jq -R . | jq -s -c .)
          echo "Collected specs for E2E tests: $specs"
          echo "specs=$specs" >> $GITHUB_OUTPUT

  e2e:
    runs-on: ubuntu-24.04
    needs: gather-e2e-specs
    strategy:
      fail-fast: false
      matrix:
        spec: ${{ fromJson(needs.gather-e2e-specs.outputs.specs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{vars.JAVA_VERSION}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{vars.JAVA_VERSION}}
          distribution: 'adopt'

      - uses: abhi1693/setup-browser@v0.3.5
        with:
          browser: chrome
          version: latest

      - name: run keycloak docker
        run: |
          docker run -d \
          --name my_keycloak \
          -e KC_BOOTSTRAP_ADMIN_USERNAME=admin26 \
          -e KC_BOOTSTRAP_ADMIN_PASSWORD=keycloak26 \
          -v ./docker/config/realm-export-pitc.json:/opt/keycloak/data/import/realm-pitc.json \
          -p 8544:8080 \
          quay.io/keycloak/keycloak:26.0.1 \
          start-dev --import-realm

      - name: start backend
        run: cd ./backend && mvn spring-boot:run -Dspring-boot.run.profiles=integration-test &

      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          spec: cypress/e2e/${{ matrix.spec }}
          start: npm start
          wait-on: 'http://pitc.okr.localhost:8080/config, http://pitc.okr.localhost:4200, http://localhost:8544'
          wait-on-timeout: 120
          browser: chrome
          headed: true
```
